#!/bin/bash
NAME=mqtt_api
DIR=/home/sysadmin/code/iot_case_h5/app/api
USER=sysadmin
GROUP=sysadmin
WORKERS=3
WORKER_CLASS=uvicorn.workers.UvicornWorker
VENV=$DIR/.venv/bin/activate
BIND_SUB=127.0.0.1:8000
BIND_PUB=127.0.0.1:8080
LOG_LEVEL=info

cd $DIR
source $VENV

exec gunicorn subscriber:app \
  --name $NAME \
  --workers $WORKERS \
  --worker-class $WORKER_CLASS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND_SUB \
  --log-level=$LOG_LEVEL \
  --log-file=-


# NOTE: Lets wait with this for now
# exec gunicorn publiser:app \
#   --name $NAME \
#   --workers $WORKERS \
#   --worker-class $WORKER_CLASS \
#   --user=$USER \
#   --group=$GROUP \
#   --bind=$BIND_PUB \
#   --log-level=$LOG_LEVEL \
#   --log-file=-

